In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
# take inputs below, calculate goal portfolio for retirement start + savings as of retirement date
# additionally, return dataframe with yearly numbers for review

# variable assignment, dollar amounts in thousands, annualized
current_year = 2021
years_to_retirement = 35
current_savings = 30
current_income = 100
income_growth = 0.04
annual_savings = 0.10 # what % of your income do you expect to save each year
annual_returns = 0.10 # what returns do you expect to get on those savings
inflation = 0.02
ss_benefits = 25 # do you expect to receive any ss benefits in retirement?
retirement_expenses_current = 80 # in today's dollars, how much do you expect to need each year in retirement?
withdraw_amount = 0.03 # how much of your savings do you expect to withdraw each year? larger = riskier

def portfolio_goal():
    # calculate goal portfolio at start of retirement
    # (inflation adjusted expenses - ss_benefits) / withdraw_amount
    
    retirement_expenses_future = retirement_expenses_current \
                                * (1 + inflation) ** years_to_retirement - ss_benefits
    portfolio_goal = retirement_expenses_future / withdraw_amount
    return round(portfolio_goal,2)



def portfolio_value():
    # for each year, calculate portfolio value, income, and savings
    # account for appreciation in portfolio value and income year to year
    # stepwise algorithm to create lists of each variable, zip the lists and create dataframe
    
    years = list(range(current_year, current_year + years_to_retirement + 1))
    year, income = current_year, current_income
    portfolio_start = [current_savings]
    incomes = []
    savings = []
    portfolio_end = []
    portfolio_value = portfolio_start[0]
    
    while year <= years[-1]:
        portfolio_value = portfolio_value * (1 + annual_returns) + income * annual_savings
        
        portfolio_end.append(round(portfolio_value,2))
        portfolio_start.append(round(portfolio_value,2))
        incomes.append(round(income,2))
        savings.append(round(income * annual_savings,2))
        
        income = income * (1 + income_growth)
        year += 1
    
    df = pd.DataFrame(list(zip(years, portfolio_start, incomes, savings, portfolio_end)),
                     columns = ['year','portfolio_start','income','savings','portfolio_end'])
    return df

goal = portfolio_goal()
df = portfolio_value()
value = df['portfolio_end'].iloc[-1]

# print('Your Portfolio Goal is %5.2f \nYour Portfolio Value is %5.2f' \
#      % (goal, df['portfolio_end'].iloc[-1]))

print(f"Your Portfolio Goal is {goal} \nYour Portfolio Value is {value}")

Your Portfolio Goal is 4499.71
Your Portfolio Value is 5395.51

In [3]:
df

    year  portfolio_start  income  savings  portfolio_end
0   2021            30.00  100.00    10.00          43.00
1   2022            43.00  104.00    10.40          57.70
2   2023            57.70  108.16    10.82          74.29
3   2024            74.29  112.49    11.25          92.96
4   2025            92.96  116.99    11.70         113.96
5   2026           113.96  121.67    12.17         137.52
6   2027           137.52  126.53    12.65         163.93
7   2028           163.93  131.59    13.16         193.48
8   2029           193.48  136.86    13.69         226.51
9   2030           226.51  142.33    14.23         263.40
10  2031           263.40  148.02    14.80         304.54
11  2032           304.54  153.95    15.39         350.39
12  2033           350.39  160.10    16.01         401.43
13  2034           401.43  166.51    16.65         458.23
14  2035           458.23  173.17    17.32         521.37
15  2036           521.37  180.09    18.01         591.51
16  2037           591.51  187.30    18.73         669.40
17  2038           669.40  194.79    19.48         755.81
18  2039           755.81  202.58    20.26         851.65
19  2040           851.65  210.68    21.07         957.89
20  2041           957.89  219.11    21.91        1075.59
21  2042          1075.59  227.88    22.79        1205.93
22  2043          1205.93  236.99    23.70        1350.23
23  2044          1350.23  246.47    24.65        1509.90
24  2045          1509.90  256.33    25.63        1686.52
25  2046          1686.52  266.58    26.66        1881.83
26  2047          1881.83  277.25    27.72        2097.74
27  2048          2097.74  288.34    28.83        2336.34
28  2049          2336.34  299.87    29.99        2599.97
29  2050          2599.97  311.87    31.19        2891.15
30  2051          2891.15  324.34    32.43        3212.70
31  2052          3212.70  337.31    33.73        3567.70
32  2053          3567.70  350.81    35.08        3959.55
33  2054          3959.55  364.84    36.48        4391.99
34  2055          4391.99  379.43    37.94        4869.13
35  2056          4869.13  394.61    39.46        5395.51