In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
# take inputs below, calculate goal portfolio for retirement start + savings as of retirement date
# additionally, return dataframe with yearly numbers for review

# variable assignment, dollar amounts in thousands
current_year = 2021
years_to_retirement = 30
current_savings = 120
current_income = 120
income_growth = 0.07
annual_savings = 0.12
annual_returns = 0.10
inflation = 0.03
ss_benefits = 25
retirement_expenses_current = 150
withdraw_amount = 0.04

# create a function that generates multiple lists
# portfolio begin, income, savings, portfolio end
# zip the lists and create dataframe

def portfolio_goal():
    retirement_expenses_future = retirement_expenses_current \
                                * (1 + inflation) ** years_to_retirement - ss_benefits
    portfolio_goal = retirement_expenses_future / withdraw_amount
    return portfolio_goal

def portfolio_value():
    years = list(range(current_year, current_year + years_to_retirement + 1))
    year, income = current_year, current_income
    portfolio_start = [current_savings]
    incomes = []
    savings = []
    portfolio_end = []
    portfolio_value = portfolio_start[0]
    
    while year <= years[-1]:
        portfolio_value = portfolio_value * (1 + annual_returns) + income * annual_savings
        portfolio_end.append(round(portfolio_value,2))
        portfolio_start.append(round(portfolio_value,2))
        incomes.append(round(income,2))
        savings.append(round(income * annual_savings,2))
        
        income = income * (1 + income_growth)
        year += 1
    
    df = pd.DataFrame(list(zip(years, portfolio_start, incomes, savings, portfolio_end)),
                     columns = ['year','portfolio_start','income','savings','portfolio_end'])
    return df

goal = portfolio_goal()
df = portfolio_value()

print('Your Portfolio Goal is %5.2f \nYour Portfolio Value is %5.2f' \
     % (goal, df['portfolio_end'].iloc[-1]))

Your Portfolio Goal is 8477.23
Your Portfolio Value is 7606.95

In [8]:
df

    year  portfolio_start  income  savings  portfolio_end
0   2021           120.00  200.00    24.00         156.00
1   2022           156.00  210.00    25.20         196.80
2   2023           196.80  220.50    26.46         242.94
3   2024           242.94  231.53    27.78         295.02
4   2025           295.02  243.10    29.17         353.69
5   2026           353.69  255.26    30.63         419.69
6   2027           419.69  268.02    32.16         493.82
7   2028           493.82  281.42    33.77         576.97
8   2029           576.97  295.49    35.46         670.13
9   2030           670.13  310.27    37.23         774.38
10  2031           774.38  325.78    39.09         890.91
11  2032           890.91  342.07    41.05        1021.05
12  2033          1021.05  359.17    43.10        1166.25
13  2034          1166.25  377.13    45.26        1328.13
14  2035          1328.13  395.99    47.52        1508.46
15  2036          1508.46  415.79    49.89        1709.20
16  2037          1709.20  436.57    52.39        1932.51
17  2038          1932.51  458.40    55.01        2180.77
18  2039          2180.77  481.32    57.76        2456.61
19  2040          2456.61  505.39    60.65        2762.92
20  2041          2762.92  530.66    63.68        3102.89
21  2042          3102.89  557.19    66.86        3480.04
22  2043          3480.04  585.05    70.21        3898.25
23  2044          3898.25  614.30    73.72        4361.79
24  2045          4361.79  645.02    77.40        4875.37
25  2046          4875.37  677.27    81.27        5444.18